version: '3.1'
services:
  database:
    image: 'mariadb:11.0'
    container_name: online_learning_platform_mariadb
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MARIADB_DATABASE}'
      - 'MYSQL_USER=${MARIADB_USER}'
      - 'MYSQL_PASSWORD=${MARIADB_PASSWORD}'
    ports:
      - '3306:3306'

  webserver:
    image: 'nginx:alpine'
    container_name: online_learning_platform_webserver
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8002:80'

  php-fpm:
    build: phpdocker/php-fpm
    container_name: online_learning_platform_php
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    container_name: online_learning_platform_phpmyadmin
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=online_learning_platform_mariadb

  mailer:
    container_name: online_learning_platform_mailer
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'

